#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username postgres --dbname "$hostname" <<-EOSQL
	CREATE USER replicator WITH REPLICATION ENCRYPTED PASSWORD 'my_replicator_password';
    SELECT * FROM pg_create_physical_replication_slot('replication_slot_read_1');
    SELECT * FROM pg_create_physical_replication_slot('replication_slot_read_2');
EOSQL
pg_basebackup -D /tmp/postgres_read_1 -S replication_slot_read_1 -X stream -P -U replicator -Fp -R 
pg_basebackup -D /tmp/postgres_read_2 -S replication_slot_read_2 -X stream -P -U replicator -Fp -R 
cp /etc/postgresql/postgresql.conf /var/lib/postgresql/data
cp /etc/postgresql/pg_hba.conf /var/lib/postgresql/data

cp /var/lib/postgresql/data/postgresql.conf /tmp/postgres_read_1/
cp /var/lib/postgresql/data/pg_hba.conf /tmp/postgres_read_1/

cp /var/lib/postgresql/data/postgresql.conf /tmp/postgres_read_2/
cp /var/lib/postgresql/data/pg_hba.conf /tmp/postgres_read_2/

cat > /tmp/postgres_read_1/postgresql.auto.conf << EOF 
# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.
primary_conninfo = 'host=main_db_three port=5432 user=replicator password=my_replicator_password'
primary_slot_name = 'replication_slot_read_1'
# restore_command = 'cp /var/lib/postgresql/data/pg_wal/%f "%p"'
EOF

cat > /tmp/postgres_read_2/postgresql.auto.conf << EOF 
# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.
primary_conninfo = 'host=main_db_three port=5432 user=replicator password=my_replicator_password'
primary_slot_name = 'replication_slot_read_2'
# restore_command = 'cp /var/lib/postgresql/data/pg_wal/%f "%p"'
EOF
